spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: devel
    password: q1w2e3r4
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    database-id: mysql
    cache-enabled: true
    jdbc-type-for-null: 'null' #注意：单引号
