spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mcms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: zhaodong123..
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
#ms:
  #diy:
    #html-dir: dist-vue
